// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: '/calc', uri: Uri.parse('/calc'), routeBuilder: b0Builder),
];

const routePaths = (path: '/', calc: '/calc');
